In [1]:
import pandas as pd

In [2]:
# Importing CSV files - different seeds
Marked_10000 = pd.read_csv('TestSetGCRMethod/metricDataFrameMarked-IF10000.csv')
Marked_Optimal = pd.read_csv('TestSetGCRMethod/metricDataFrameMarked-IFOptimal.csv')

Method1_10000 = pd.read_csv('TestSetGCRMethod/metricDataFrameGCR-IF10000-1-gcr.csv')
Method2_10000 = pd.read_csv('TestSetGCRMethod/metricDataFrameGCR-IF10000-2-gcr.csv')
Method3_10000 = pd.read_csv('TestSetGCRMethod/metricDataFrameGCR-IF10000-3-gcr.csv')

Method1_Optimal = pd.read_csv('TestSetGCRMethod/metricDataFrameGCR-IFOptimal-1-gcr.csv')
Method2_Optimal = pd.read_csv('TestSetGCRMethod/metricDataFrameGCR-IFOptimal-2-gcr.csv')
Method3_Optimal = pd.read_csv('TestSetGCRMethod/metricDataFrameGCR-IFOptimal-3-gcr.csv')

In [3]:
#Getting mean values from DataFrames; Dropping first row
Method1_10000Mean = Method1_10000.mean()
Method1_10000Mean = Method1_10000Mean.drop(['Unnamed: 0'])

Method2_10000Mean = Method2_10000.mean()
Method2_10000Mean = Method2_10000Mean.drop(['Unnamed: 0'])

Method3_10000Mean = Method3_10000.mean()
Method3_10000Mean = Method3_10000Mean.drop(['Unnamed: 0'])

Method1_OptimalMean = Method1_Optimal.mean()
Method1_OptimalMean = Method1_OptimalMean.drop(['Unnamed: 0'])

Method2_OptimalMean = Method2_Optimal.mean()
Method2_OptimalMean = Method2_OptimalMean.drop(['Unnamed: 0'])

Method3_OptimalMean = Method3_Optimal.mean()
Method3_OptimalMean = Method3_OptimalMean.drop(['Unnamed: 0'])

In [4]:
# Creating DataFrame for comparing GCR Methods - Impact Factor = 10000
dfCompare10000 = pd.concat([Marked_10000['GCR / Marked'], 
                            Method1_10000['GCR / Marked'], 
                            Method2_10000['GCR / Marked'], 
                            Method3_10000['GCR / Marked']], axis = 1)
dfCompare10000.columns = ['Marked (10000)', 'Method 1', 'Method 2', 'Method 3']
dfCompare10000

   Marked (10000)  Method 1  Method 2  Method 3
0        0.773839  0.766296  0.771700  0.773852
1        0.757096  0.729697  0.747282  0.756358
2        0.862074  0.681772  0.804328  0.861823
3        0.521476  0.490225  0.510315  0.521404
4        0.613648  0.535253  0.565976  0.600178

In [5]:
# Creating DataFrame for comparing GCR Methods - Impact Factor = Optimal
dfCompareOptimal = pd.concat([Marked_Optimal['GCR / Marked'], 
                              Method1_Optimal['GCR / Marked'], 
                              Method2_Optimal['GCR / Marked'], 
                              Method3_Optimal['GCR / Marked']], axis = 1)
dfCompareOptimal.columns = ['Marked (Optimal)', 'Method 1', 'Method 2', 'Method 3']
dfCompareOptimal

   Marked (Optimal)  Method 1  Method 2  Method 3
0          0.734733  0.734312  0.734608  0.734898
1          0.725752  0.723286  0.724185  0.725229
2          0.818929  0.816305  0.817025  0.818750
3          0.501588  0.487917  0.496881  0.501555
4          0.598889  0.576891  0.583799  0.589049

In [6]:
dfCompare10000.describe()

       Marked (10000)  Method 1  Method 2  Method 3
count        5.000000  5.000000  5.000000  5.000000
mean         0.705627  0.640649  0.679920  0.702723
std          0.136152  0.121597  0.132465  0.138421
min          0.521476  0.490225  0.510315  0.521404
25%          0.613648  0.535253  0.565976  0.600178
50%          0.757096  0.681772  0.747282  0.756358
75%          0.773839  0.729697  0.771700  0.773852
max          0.862074  0.766296  0.804328  0.861823

In [7]:
dfCompareOptimal.describe()

       Marked (Optimal)  Method 1  Method 2  Method 3
count          5.000000  5.000000  5.000000  5.000000
mean           0.675978  0.667742  0.671299  0.673896
std            0.125219  0.132456  0.128568  0.126727
min            0.501588  0.487917  0.496881  0.501555
25%            0.598889  0.576891  0.583799  0.589049
50%            0.725752  0.723286  0.724185  0.725229
75%            0.734733  0.734312  0.734608  0.734898
max            0.818929  0.816305  0.817025  0.818750